### ISSUE TITLE
在群内发送“光遇菜单”后报错

### ISSUE THREAD

**Issue by QSlotus** [Kaguya233qwq/nonebot_plugin_sky#16]
日志如下：
```
03-28 13:21:20 [SUCCESS] nonebot | OneBot V11 1759585224 | [message.group.normal]: Message 848010765 from 2478314183@[群:822920416] '光遇菜单'
03-28 13:21:20 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_sky, lineno=32)
03-28 13:21:20 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_sky, lineno=32) running complete
03-28 13:21:20 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_sky, lineno=32) failed.
Traceback (most recent call last):
  File "/data/nb/bot.py", line 18, in <module>
    nonebot.run()
  File "/data/nb/.venv/lib/python3.10/site-packages/nonebot/__init__.py", line 333, in run
    get_driver().run(*args, **kwargs)
  File "/data/nb/.venv/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 185, in run
    uvicorn.run(
  File "/data/nb/.venv/lib/python3.10/site-packages/uvicorn/main.py", line 587, in run
    server.run()
  File "/data/nb/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 62, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/data/nb/.venv/lib/python3.10/site-packages/nonebot/message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "/data/nb/.venv/lib/python3.10/site-packages/nonebot/message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/data/nb/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 842, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/data/nb/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 817, in simple_run
    await handler(
  File "/data/nb/.venv/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 106, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/data/nb/.venv/lib/python3.10/site-packages/nonebot_plugin_sky/__init__.py", line 97, in menu_handle
    await Menu.send(
  File "/data/nb/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 558, in send
    return await bot.send(event=event, message=_message, **kwargs)
  File "/data/nb/.venv/lib/python3.10/site-packages/nonebot/adapters/onebot/v11/bot.py", line 228, in send
    return await self.__class__.send_handler(self, event, message, **kwargs)
  File "/data/nb/.venv/lib/python3.10/site-packages/nonebot/adapters/onebot/v11/bot.py", line 181, in send
    return await bot.send_msg(**params)
  File "/data/nb/.venv/lib/python3.10/site-packages/nonebot/internal/adapter/bot.py", line 122, in call_api
    raise exception
  File "/data/nb/.venv/lib/python3.10/site-packages/nonebot/internal/adapter/bot.py", line 97, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "/data/nb/.venv/lib/python3.10/site-packages/nonebot/adapters/onebot/v11/adapter.py", line 147, in _call_api
    return handle_api_result(await self._result_store.fetch(seq, timeout))
  File "/data/nb/.venv/lib/python3.10/site-packages/nonebot/adapters/onebot/v11/utils.py", line 58, in handle_api_result
    raise ActionFailed(**result)
nonebot.adapters.onebot.v11.exception.ActionFailed: ActionFailed(status='failed', retcode=200, data=None, echo='9')
```

使用的协议端是[github.com/KonataDev/Lagrange.Core/](https://github.com/KonataDev/Lagrange.Core/)

**Comment by Kaguya233qwq** [comment]
该路径问题已修复，现能在Lagrange上正常发送消息和图片文件
